function generateImage(obj){
				id=obj.id;
				if(id==1){
				  document.getElementById("myimage").src="pic1.png"
				}
				if(id==2){
				  document.getElementById("myimage").src="pic2.png"
				}
				if(id==3){
				  document.getElementById("myimage").src="pic3.png"
				}
				if(id==4){
				  document.getElementById("myimage").src="pic4.png"
				}
				if(id==5){
				  document.getElementById("myimage").src="pic5.png"
				}
				if(id==6){
				  document.getElementById("myimage").src="pic6.png"
				}
}
